import type { Metadata } from "next";
import {
  Short_Stack,
  Tiro_Devanagari_Marathi,
  McLaren,
} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Image from "next/image";
import heroImage from "@/public/hero.svg";
import Footer from "@/components/footer";
import AddCollabButton from "@/components/newcollabhover";
import { ToastContainer } from "react-toastify";

export const Tiro_Devanagari_MarathiFont = Tiro_Devanagari_Marathi({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-manjari",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Stack+Sans+Headline:wght@200..700&family=Stack+Sans+Notch:wght@200..700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`stack-sans-notch antialiased text-[#121212] relative`}
        style={{
          // remove scrollbar
          scrollbarWidth: "none",
        }}
      >
        <ToastContainer autoClose={2000} hideProgressBar stacked />
        {/* Static Background Image */}
        <Image
          src={heroImage}
          alt="Hero Image"
          layout="fill"
          objectFit="cover"
          priority
          className="-z-20 opacity-95 fixed inset-0"
        />
        <div className="w-full z-10 absolute left-0 top-0 bg-white/30 backdrop-blur-2xl ">
          <Navigation />
        </div>
        <AddCollabButton />

        <main
          className="relative h-screen overflow-y-auto"
          style={{
            // remove scrollbar
            scrollbarWidth: "none",
          }}
        >
          {children}

          <Footer />
        </main>
      </body>
    </html>
  );
}
