import type { Metadata } from "next";
import {
  Lilita_One,
  Tiro_Devanagari_Marathi,
  McLaren,
  Cactus_Classical_Serif,
} from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation";
import Image from "next/image";
import heroImage from "@/public/hero.svg";
import Footer from "@/components/footer";
import AddCollabButton from "@/components/newcollabhover";

export const Tiro_Devanagari_MarathiFont = Tiro_Devanagari_Marathi({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-manjari",
});

export const McLarenFont = McLaren({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-mclaren",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${McLarenFont.className}  antialiased text-[#121212] relative`}>
        {/* Static Background Image */}
        <Image
          src={heroImage}
          alt="Hero Image"
          layout="fill"
          objectFit="cover"
          priority
          className="-z-10 opacity-95 fixed inset-0"
        />
        
        <Navigation />
        <AddCollabButton/>

        <main className="relative z-10 h-screen overflow-y-auto">
          {children}
          
        <Footer />
        </main>

      </body>
    </html>
  );
}